NETBEGIN 1
CLUBEGIN 1
PERBEGIN 1
CLSBEGIN 1
HIEBEGIN 1
VECBEGIN 1
% Reading Network   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\era23.net
N 1 RDN C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\era23.net
% Reading Partition   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\era23_testCommunity.clu
C 1 RDC C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\era23_testCommunity.clu
% Extracting Subnetworks induced by each selected Cluster
N 395 EXTNETALL 1 1 [1-*]
% All degree centrality of 2. Subnetwork of N1 induced by C1 [1]
V 1 DEGV 2 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_1.vec
V 1 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_1.vec 0
% All degree centrality of 3. Subnetwork of N1 induced by C1 [2]
V 2 DEGV 3 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_2.vec
V 2 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_2.vec 0
% All degree centrality of 4. Subnetwork of N1 induced by C1 [3]
V 3 DEGV 4 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_3.vec
V 3 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_3.vec 0
% All degree centrality of 5. Subnetwork of N1 induced by C1 [4]
V 4 DEGV 5 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_4.vec
V 4 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_4.vec 0
% All degree centrality of 6. Subnetwork of N1 induced by C1 [5]
V 5 DEGV 6 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_5.vec
V 5 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_5.vec 0
% All degree centrality of 7. Subnetwork of N1 induced by C1 [6]
V 6 DEGV 7 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_6.vec
V 6 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_6.vec 0
% All degree centrality of 8. Subnetwork of N1 induced by C1 [7]
V 7 DEGV 8 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_7.vec
V 7 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_7.vec 0
% All degree centrality of 9. Subnetwork of N1 induced by C1 [8]
V 8 DEGV 9 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_8.vec
V 8 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_8.vec 0
% All degree centrality of 10. Subnetwork of N1 induced by C1 [9]
V 9 DEGV 10 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_9.vec
V 9 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_9.vec 0
% All degree centrality of 11. Subnetwork of N1 induced by C1 [10]
V 10 DEGV 11 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_10.vec
V 10 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_10.vec 0
% All degree centrality of 12. Subnetwork of N1 induced by C1 [11]
V 11 DEGV 12 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_11.vec
V 11 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_11.vec 0
% All degree centrality of 13. Subnetwork of N1 induced by C1 [12]
V 12 DEGV 13 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_12.vec
V 12 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_12.vec 0
% All degree centrality of 14. Subnetwork of N1 induced by C1 [13]
V 13 DEGV 14 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_13.vec
V 13 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_13.vec 0
% All degree centrality of 15. Subnetwork of N1 induced by C1 [14]
V 14 DEGV 15 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_14.vec
V 14 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_14.vec 0
% All degree centrality of 16. Subnetwork of N1 induced by C1 [15]
V 15 DEGV 16 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_15.vec
V 15 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_15.vec 0
% All degree centrality of 17. Subnetwork of N1 induced by C1 [16]
V 16 DEGV 17 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_16.vec
V 16 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_16.vec 0
% All degree centrality of 18. Subnetwork of N1 induced by C1 [17]
V 17 DEGV 18 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_17.vec
V 17 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_17.vec 0
% All degree centrality of 19. Subnetwork of N1 induced by C1 [18]
V 18 DEGV 19 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_18.vec
V 18 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_18.vec 0
% All degree centrality of 20. Subnetwork of N1 induced by C1 [19]
V 19 DEGV 20 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_19.vec
V 19 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_19.vec 0
% All degree centrality of 21. Subnetwork of N1 induced by C1 [20]
V 20 DEGV 21 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_20.vec
V 20 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_20.vec 0
% All degree centrality of 22. Subnetwork of N1 induced by C1 [21]
V 21 DEGV 22 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_21.vec
V 21 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_21.vec 0
% All degree centrality of 23. Subnetwork of N1 induced by C1 [22]
V 22 DEGV 23 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_22.vec
V 22 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_22.vec 0
% All degree centrality of 24. Subnetwork of N1 induced by C1 [23]
V 23 DEGV 24 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_23.vec
V 23 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_23.vec 0
% All degree centrality of 25. Subnetwork of N1 induced by C1 [24]
V 24 DEGV 25 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_24.vec
V 24 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_24.vec 0
% All degree centrality of 26. Subnetwork of N1 induced by C1 [25]
V 25 DEGV 26 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_25.vec
V 25 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_25.vec 0
% All degree centrality of 27. Subnetwork of N1 induced by C1 [26]
V 26 DEGV 27 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_26.vec
V 26 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_26.vec 0
% All degree centrality of 28. Subnetwork of N1 induced by C1 [27]
V 27 DEGV 28 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_27.vec
V 27 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_27.vec 0
% All degree centrality of 29. Subnetwork of N1 induced by C1 [28]
V 28 DEGV 29 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_28.vec
V 28 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_28.vec 0
% All degree centrality of 30. Subnetwork of N1 induced by C1 [29]
V 29 DEGV 30 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_29.vec
V 29 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_29.vec 0
% All degree centrality of 31. Subnetwork of N1 induced by C1 [30]
V 30 DEGV 31 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_30.vec
V 30 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_30.vec 0
% All degree centrality of 32. Subnetwork of N1 induced by C1 [31]
V 31 DEGV 32 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_31.vec
V 31 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_31.vec 0
% All degree centrality of 33. Subnetwork of N1 induced by C1 [32]
V 32 DEGV 33 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_32.vec
V 32 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_32.vec 0
% All degree centrality of 34. Subnetwork of N1 induced by C1 [33]
V 33 DEGV 34 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_33.vec
V 33 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_33.vec 0
% All degree centrality of 35. Subnetwork of N1 induced by C1 [34]
V 34 DEGV 35 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_34.vec
V 34 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_34.vec 0
% All degree centrality of 36. Subnetwork of N1 induced by C1 [35]
V 35 DEGV 36 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_35.vec
V 35 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_35.vec 0
% All degree centrality of 37. Subnetwork of N1 induced by C1 [36]
V 36 DEGV 37 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_36.vec
V 36 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_36.vec 0
% All degree centrality of 38. Subnetwork of N1 induced by C1 [37]
V 37 DEGV 38 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_37.vec
V 37 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_37.vec 0
% All degree centrality of 39. Subnetwork of N1 induced by C1 [38]
V 38 DEGV 39 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_38.vec
V 38 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_38.vec 0
% All degree centrality of 40. Subnetwork of N1 induced by C1 [39]
V 39 DEGV 40 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_39.vec
V 39 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_39.vec 0
% All degree centrality of 41. Subnetwork of N1 induced by C1 [40]
V 40 DEGV 41 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_40.vec
V 40 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_40.vec 0
% All degree centrality of 42. Subnetwork of N1 induced by C1 [41]
V 41 DEGV 42 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_41.vec
V 41 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_41.vec 0
% All degree centrality of 43. Subnetwork of N1 induced by C1 [42]
V 42 DEGV 43 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_42.vec
V 42 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_42.vec 0
% All degree centrality of 44. Subnetwork of N1 induced by C1 [43]
V 43 DEGV 44 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_43.vec
V 43 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_43.vec 0
% All degree centrality of 45. Subnetwork of N1 induced by C1 [44]
V 44 DEGV 45 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_44.vec
V 44 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_44.vec 0
% All degree centrality of 46. Subnetwork of N1 induced by C1 [45]
V 45 DEGV 46 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_45.vec
V 45 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_45.vec 0
% All degree centrality of 47. Subnetwork of N1 induced by C1 [46]
V 46 DEGV 47 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_46.vec
V 46 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_46.vec 0
% All degree centrality of 48. Subnetwork of N1 induced by C1 [47]
V 47 DEGV 48 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_47.vec
V 47 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_47.vec 0
% All degree centrality of 49. Subnetwork of N1 induced by C1 [48]
V 48 DEGV 49 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_48.vec
V 48 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_48.vec 0
% All degree centrality of 50. Subnetwork of N1 induced by C1 [49]
V 49 DEGV 50 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_49.vec
V 49 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_49.vec 0
% All degree centrality of 51. Subnetwork of N1 induced by C1 [50]
V 50 DEGV 51 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_50.vec
V 50 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_50.vec 0
% All degree centrality of 52. Subnetwork of N1 induced by C1 [51]
V 51 DEGV 52 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_51.vec
V 51 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_51.vec 0
% All degree centrality of 53. Subnetwork of N1 induced by C1 [52]
V 52 DEGV 53 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_52.vec
V 52 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_52.vec 0
% All degree centrality of 54. Subnetwork of N1 induced by C1 [53]
V 53 DEGV 54 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_53.vec
V 53 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_53.vec 0
% All degree centrality of 55. Subnetwork of N1 induced by C1 [54]
V 54 DEGV 55 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_54.vec
V 54 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_54.vec 0
% All degree centrality of 56. Subnetwork of N1 induced by C1 [55]
V 55 DEGV 56 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_55.vec
V 55 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_55.vec 0
% All degree centrality of 57. Subnetwork of N1 induced by C1 [56]
V 56 DEGV 57 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_56.vec
V 56 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_56.vec 0
% All degree centrality of 58. Subnetwork of N1 induced by C1 [57]
V 57 DEGV 58 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_57.vec
V 57 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_57.vec 0
% All degree centrality of 59. Subnetwork of N1 induced by C1 [58]
V 58 DEGV 59 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_58.vec
V 58 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_58.vec 0
% All degree centrality of 60. Subnetwork of N1 induced by C1 [59]
V 59 DEGV 60 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_59.vec
V 59 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_59.vec 0
% All degree centrality of 61. Subnetwork of N1 induced by C1 [60]
V 60 DEGV 61 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_60.vec
V 60 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_60.vec 0
% All degree centrality of 62. Subnetwork of N1 induced by C1 [61]
V 61 DEGV 62 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_61.vec
V 61 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_61.vec 0
% All degree centrality of 63. Subnetwork of N1 induced by C1 [62]
V 62 DEGV 63 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_62.vec
V 62 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_62.vec 0
% All degree centrality of 64. Subnetwork of N1 induced by C1 [63]
V 63 DEGV 64 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_63.vec
V 63 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_63.vec 0
% All degree centrality of 65. Subnetwork of N1 induced by C1 [64]
V 64 DEGV 65 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_64.vec
V 64 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_64.vec 0
% All degree centrality of 66. Subnetwork of N1 induced by C1 [65]
V 65 DEGV 66 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_65.vec
V 65 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_65.vec 0
% All degree centrality of 67. Subnetwork of N1 induced by C1 [66]
V 66 DEGV 67 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_66.vec
V 66 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_66.vec 0
% All degree centrality of 68. Subnetwork of N1 induced by C1 [67]
V 67 DEGV 68 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_67.vec
V 67 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_67.vec 0
% All degree centrality of 69. Subnetwork of N1 induced by C1 [68]
V 68 DEGV 69 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_68.vec
V 68 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_68.vec 0
% All degree centrality of 70. Subnetwork of N1 induced by C1 [69]
V 69 DEGV 70 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_69.vec
V 69 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_69.vec 0
% All degree centrality of 71. Subnetwork of N1 induced by C1 [70]
V 70 DEGV 71 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_70.vec
V 70 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_70.vec 0
% All degree centrality of 72. Subnetwork of N1 induced by C1 [71]
V 71 DEGV 72 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_71.vec
V 71 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_71.vec 0
% All degree centrality of 73. Subnetwork of N1 induced by C1 [72]
V 72 DEGV 73 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_72.vec
V 72 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_72.vec 0
% All degree centrality of 74. Subnetwork of N1 induced by C1 [73]
V 73 DEGV 74 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_73.vec
V 73 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_73.vec 0
% All degree centrality of 75. Subnetwork of N1 induced by C1 [74]
V 74 DEGV 75 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_74.vec
V 74 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_74.vec 0
% All degree centrality of 76. Subnetwork of N1 induced by C1 [75]
V 75 DEGV 76 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_75.vec
V 75 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_75.vec 0
% All degree centrality of 77. Subnetwork of N1 induced by C1 [76]
V 76 DEGV 77 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_76.vec
V 76 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_76.vec 0
% All degree centrality of 78. Subnetwork of N1 induced by C1 [77]
V 77 DEGV 78 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_77.vec
V 77 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_77.vec 0
% All degree centrality of 79. Subnetwork of N1 induced by C1 [78]
V 78 DEGV 79 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_78.vec
V 78 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_78.vec 0
% All degree centrality of 80. Subnetwork of N1 induced by C1 [79]
V 79 DEGV 80 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_79.vec
V 79 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_79.vec 0
% All degree centrality of 81. Subnetwork of N1 induced by C1 [80]
V 80 DEGV 81 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_80.vec
V 80 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_80.vec 0
% All degree centrality of 82. Subnetwork of N1 induced by C1 [81]
V 81 DEGV 82 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_81.vec
V 81 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_81.vec 0
% All degree centrality of 83. Subnetwork of N1 induced by C1 [82]
V 82 DEGV 83 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_82.vec
V 82 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_82.vec 0
% All degree centrality of 84. Subnetwork of N1 induced by C1 [83]
V 83 DEGV 84 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_83.vec
V 83 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_83.vec 0
% All degree centrality of 85. Subnetwork of N1 induced by C1 [84]
V 84 DEGV 85 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_84.vec
V 84 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_84.vec 0
% All degree centrality of 86. Subnetwork of N1 induced by C1 [85]
V 85 DEGV 86 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_85.vec
V 85 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_85.vec 0
% All degree centrality of 87. Subnetwork of N1 induced by C1 [86]
V 86 DEGV 87 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_86.vec
V 86 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_86.vec 0
% All degree centrality of 88. Subnetwork of N1 induced by C1 [87]
V 87 DEGV 88 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_87.vec
V 87 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_87.vec 0
% All degree centrality of 89. Subnetwork of N1 induced by C1 [88]
V 88 DEGV 89 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_88.vec
V 88 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_88.vec 0
% All degree centrality of 90. Subnetwork of N1 induced by C1 [89]
V 89 DEGV 90 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_89.vec
V 89 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_89.vec 0
% All degree centrality of 91. Subnetwork of N1 induced by C1 [90]
V 90 DEGV 91 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_90.vec
V 90 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_90.vec 0
% All degree centrality of 92. Subnetwork of N1 induced by C1 [91]
V 91 DEGV 92 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_91.vec
V 91 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_91.vec 0
% All degree centrality of 93. Subnetwork of N1 induced by C1 [92]
V 92 DEGV 93 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_92.vec
V 92 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_92.vec 0
% All degree centrality of 94. Subnetwork of N1 induced by C1 [93]
V 93 DEGV 94 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_93.vec
V 93 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_93.vec 0
% All degree centrality of 95. Subnetwork of N1 induced by C1 [94]
V 94 DEGV 95 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_94.vec
V 94 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_94.vec 0
% All degree centrality of 96. Subnetwork of N1 induced by C1 [95]
V 95 DEGV 96 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_95.vec
V 95 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_95.vec 0
% All degree centrality of 97. Subnetwork of N1 induced by C1 [96]
V 96 DEGV 97 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_96.vec
V 96 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_96.vec 0
% All degree centrality of 98. Subnetwork of N1 induced by C1 [97]
V 97 DEGV 98 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_97.vec
V 97 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_97.vec 0
% All degree centrality of 99. Subnetwork of N1 induced by C1 [98]
V 98 DEGV 99 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_98.vec
V 98 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_98.vec 0
% All degree centrality of 100. Subnetwork of N1 induced by C1 [99]
V 99 DEGV 100 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_99.vec
V 99 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_99.vec 0
% All degree centrality of 101. Subnetwork of N1 induced by C1 [100]
V 100 DEGV 101 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_100.vec
V 100 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_100.vec 0
% All degree centrality of 102. Subnetwork of N1 induced by C1 [101]
V 101 DEGV 102 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_101.vec
V 101 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_101.vec 0
% All degree centrality of 103. Subnetwork of N1 induced by C1 [102]
V 102 DEGV 103 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_102.vec
V 102 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_102.vec 0
% All degree centrality of 104. Subnetwork of N1 induced by C1 [103]
V 103 DEGV 104 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_103.vec
V 103 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_103.vec 0
% All degree centrality of 105. Subnetwork of N1 induced by C1 [104]
V 104 DEGV 105 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_104.vec
V 104 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_104.vec 0
% All degree centrality of 106. Subnetwork of N1 induced by C1 [105]
V 105 DEGV 106 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_105.vec
V 105 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_105.vec 0
% All degree centrality of 107. Subnetwork of N1 induced by C1 [106]
V 106 DEGV 107 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_106.vec
V 106 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_106.vec 0
% All degree centrality of 108. Subnetwork of N1 induced by C1 [107]
V 107 DEGV 108 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_107.vec
V 107 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_107.vec 0
% All degree centrality of 109. Subnetwork of N1 induced by C1 [108]
V 108 DEGV 109 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_108.vec
V 108 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_108.vec 0
% All degree centrality of 110. Subnetwork of N1 induced by C1 [109]
V 109 DEGV 110 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_109.vec
V 109 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_109.vec 0
% All degree centrality of 111. Subnetwork of N1 induced by C1 [110]
V 110 DEGV 111 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_110.vec
V 110 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_110.vec 0
% All degree centrality of 112. Subnetwork of N1 induced by C1 [111]
V 111 DEGV 112 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_111.vec
V 111 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_111.vec 0
% All degree centrality of 113. Subnetwork of N1 induced by C1 [112]
V 112 DEGV 113 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_112.vec
V 112 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_112.vec 0
% All degree centrality of 114. Subnetwork of N1 induced by C1 [113]
V 113 DEGV 114 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_113.vec
V 113 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_113.vec 0
% All degree centrality of 115. Subnetwork of N1 induced by C1 [114]
V 114 DEGV 115 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_114.vec
V 114 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_114.vec 0
% All degree centrality of 116. Subnetwork of N1 induced by C1 [115]
V 115 DEGV 116 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_115.vec
V 115 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_115.vec 0
% All degree centrality of 117. Subnetwork of N1 induced by C1 [116]
V 116 DEGV 117 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_116.vec
V 116 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_116.vec 0
% All degree centrality of 118. Subnetwork of N1 induced by C1 [117]
V 117 DEGV 118 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_117.vec
V 117 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_117.vec 0
% All degree centrality of 119. Subnetwork of N1 induced by C1 [118]
V 118 DEGV 119 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_118.vec
V 118 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_118.vec 0
% All degree centrality of 120. Subnetwork of N1 induced by C1 [119]
V 119 DEGV 120 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_119.vec
V 119 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_119.vec 0
% All degree centrality of 121. Subnetwork of N1 induced by C1 [120]
V 120 DEGV 121 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_120.vec
V 120 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_120.vec 0
% All degree centrality of 122. Subnetwork of N1 induced by C1 [121]
V 121 DEGV 122 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_121.vec
V 121 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_121.vec 0
% All degree centrality of 123. Subnetwork of N1 induced by C1 [122]
V 122 DEGV 123 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_122.vec
V 122 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_122.vec 0
% All degree centrality of 124. Subnetwork of N1 induced by C1 [123]
V 123 DEGV 124 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_123.vec
V 123 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_123.vec 0
% All degree centrality of 125. Subnetwork of N1 induced by C1 [124]
V 124 DEGV 125 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_124.vec
V 124 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_124.vec 0
% All degree centrality of 126. Subnetwork of N1 induced by C1 [125]
V 125 DEGV 126 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_125.vec
V 125 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_125.vec 0
% All degree centrality of 127. Subnetwork of N1 induced by C1 [126]
V 126 DEGV 127 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_126.vec
V 126 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_126.vec 0
% All degree centrality of 128. Subnetwork of N1 induced by C1 [127]
V 127 DEGV 128 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_127.vec
V 127 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_127.vec 0
% All degree centrality of 129. Subnetwork of N1 induced by C1 [128]
V 128 DEGV 129 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_128.vec
V 128 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_128.vec 0
% All degree centrality of 130. Subnetwork of N1 induced by C1 [129]
V 129 DEGV 130 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_129.vec
V 129 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_129.vec 0
% All degree centrality of 131. Subnetwork of N1 induced by C1 [130]
V 130 DEGV 131 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_130.vec
V 130 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_130.vec 0
% All degree centrality of 132. Subnetwork of N1 induced by C1 [131]
V 131 DEGV 132 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_131.vec
V 131 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_131.vec 0
% All degree centrality of 133. Subnetwork of N1 induced by C1 [132]
V 132 DEGV 133 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_132.vec
V 132 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_132.vec 0
% All degree centrality of 134. Subnetwork of N1 induced by C1 [133]
V 133 DEGV 134 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_133.vec
V 133 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_133.vec 0
% All degree centrality of 135. Subnetwork of N1 induced by C1 [134]
V 134 DEGV 135 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_134.vec
V 134 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_134.vec 0
% All degree centrality of 136. Subnetwork of N1 induced by C1 [135]
V 135 DEGV 136 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_135.vec
V 135 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_135.vec 0
% All degree centrality of 137. Subnetwork of N1 induced by C1 [136]
V 136 DEGV 137 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_136.vec
V 136 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_136.vec 0
% All degree centrality of 138. Subnetwork of N1 induced by C1 [137]
V 137 DEGV 138 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_137.vec
V 137 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_137.vec 0
% All degree centrality of 139. Subnetwork of N1 induced by C1 [138]
V 138 DEGV 139 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_138.vec
V 138 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_138.vec 0
% All degree centrality of 140. Subnetwork of N1 induced by C1 [139]
V 139 DEGV 140 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_139.vec
V 139 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_139.vec 0
% All degree centrality of 141. Subnetwork of N1 induced by C1 [140]
V 140 DEGV 141 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_140.vec
V 140 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_140.vec 0
% All degree centrality of 142. Subnetwork of N1 induced by C1 [141]
V 141 DEGV 142 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_141.vec
V 141 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_141.vec 0
% All degree centrality of 143. Subnetwork of N1 induced by C1 [142]
V 142 DEGV 143 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_142.vec
V 142 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_142.vec 0
% All degree centrality of 144. Subnetwork of N1 induced by C1 [143]
V 143 DEGV 144 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_143.vec
V 143 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_143.vec 0
% All degree centrality of 145. Subnetwork of N1 induced by C1 [144]
V 144 DEGV 145 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_144.vec
V 144 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_144.vec 0
% All degree centrality of 146. Subnetwork of N1 induced by C1 [145]
V 145 DEGV 146 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_145.vec
V 145 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_145.vec 0
% All degree centrality of 147. Subnetwork of N1 induced by C1 [146]
V 146 DEGV 147 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_146.vec
V 146 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_146.vec 0
% All degree centrality of 148. Subnetwork of N1 induced by C1 [147]
V 147 DEGV 148 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_147.vec
V 147 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_147.vec 0
% All degree centrality of 149. Subnetwork of N1 induced by C1 [148]
V 148 DEGV 149 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_148.vec
V 148 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_148.vec 0
% All degree centrality of 150. Subnetwork of N1 induced by C1 [149]
V 149 DEGV 150 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_149.vec
V 149 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_149.vec 0
% All degree centrality of 151. Subnetwork of N1 induced by C1 [150]
V 150 DEGV 151 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_150.vec
V 150 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_150.vec 0
% All degree centrality of 152. Subnetwork of N1 induced by C1 [151]
V 151 DEGV 152 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_151.vec
V 151 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_151.vec 0
% All degree centrality of 153. Subnetwork of N1 induced by C1 [152]
V 152 DEGV 153 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_152.vec
V 152 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_152.vec 0
% All degree centrality of 154. Subnetwork of N1 induced by C1 [153]
V 153 DEGV 154 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_153.vec
V 153 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_153.vec 0
% All degree centrality of 155. Subnetwork of N1 induced by C1 [154]
V 154 DEGV 155 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_154.vec
V 154 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_154.vec 0
% All degree centrality of 156. Subnetwork of N1 induced by C1 [155]
V 155 DEGV 156 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_155.vec
V 155 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_155.vec 0
% All degree centrality of 157. Subnetwork of N1 induced by C1 [156]
V 156 DEGV 157 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_156.vec
V 156 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_156.vec 0
% All degree centrality of 158. Subnetwork of N1 induced by C1 [157]
V 157 DEGV 158 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_157.vec
V 157 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_157.vec 0
% All degree centrality of 159. Subnetwork of N1 induced by C1 [158]
V 158 DEGV 159 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_158.vec
V 158 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_158.vec 0
% All degree centrality of 160. Subnetwork of N1 induced by C1 [159]
V 159 DEGV 160 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_159.vec
V 159 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_159.vec 0
% All degree centrality of 161. Subnetwork of N1 induced by C1 [160]
V 160 DEGV 161 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_160.vec
V 160 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_160.vec 0
% All degree centrality of 162. Subnetwork of N1 induced by C1 [161]
V 161 DEGV 162 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_161.vec
V 161 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_161.vec 0
% All degree centrality of 163. Subnetwork of N1 induced by C1 [162]
V 162 DEGV 163 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_162.vec
V 162 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_162.vec 0
% All degree centrality of 164. Subnetwork of N1 induced by C1 [163]
V 163 DEGV 164 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_163.vec
V 163 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_163.vec 0
% All degree centrality of 165. Subnetwork of N1 induced by C1 [164]
V 164 DEGV 165 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_164.vec
V 164 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_164.vec 0
% All degree centrality of 166. Subnetwork of N1 induced by C1 [165]
V 165 DEGV 166 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_165.vec
V 165 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_165.vec 0
% All degree centrality of 167. Subnetwork of N1 induced by C1 [166]
V 166 DEGV 167 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_166.vec
V 166 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_166.vec 0
% All degree centrality of 168. Subnetwork of N1 induced by C1 [167]
V 167 DEGV 168 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_167.vec
V 167 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_167.vec 0
% All degree centrality of 169. Subnetwork of N1 induced by C1 [168]
V 168 DEGV 169 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_168.vec
V 168 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_168.vec 0
% All degree centrality of 170. Subnetwork of N1 induced by C1 [169]
V 169 DEGV 170 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_169.vec
V 169 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_169.vec 0
% All degree centrality of 171. Subnetwork of N1 induced by C1 [170]
V 170 DEGV 171 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_170.vec
V 170 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_170.vec 0
% All degree centrality of 172. Subnetwork of N1 induced by C1 [171]
V 171 DEGV 172 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_171.vec
V 171 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_171.vec 0
% All degree centrality of 173. Subnetwork of N1 induced by C1 [172]
V 172 DEGV 173 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_172.vec
V 172 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_172.vec 0
% All degree centrality of 174. Subnetwork of N1 induced by C1 [173]
V 173 DEGV 174 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_173.vec
V 173 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_173.vec 0
% All degree centrality of 175. Subnetwork of N1 induced by C1 [174]
V 174 DEGV 175 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_174.vec
V 174 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_174.vec 0
% All degree centrality of 176. Subnetwork of N1 induced by C1 [175]
V 175 DEGV 176 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_175.vec
V 175 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_175.vec 0
% All degree centrality of 177. Subnetwork of N1 induced by C1 [176]
V 176 DEGV 177 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_176.vec
V 176 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_176.vec 0
% All degree centrality of 178. Subnetwork of N1 induced by C1 [177]
V 177 DEGV 178 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_177.vec
V 177 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_177.vec 0
% All degree centrality of 179. Subnetwork of N1 induced by C1 [178]
V 178 DEGV 179 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_178.vec
V 178 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_178.vec 0
% All degree centrality of 180. Subnetwork of N1 induced by C1 [179]
V 179 DEGV 180 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_179.vec
V 179 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_179.vec 0
% All degree centrality of 181. Subnetwork of N1 induced by C1 [180]
V 180 DEGV 181 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_180.vec
V 180 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_180.vec 0
% All degree centrality of 182. Subnetwork of N1 induced by C1 [181]
V 181 DEGV 182 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_181.vec
V 181 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_181.vec 0
% All degree centrality of 183. Subnetwork of N1 induced by C1 [182]
V 182 DEGV 183 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_182.vec
V 182 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_182.vec 0
% All degree centrality of 184. Subnetwork of N1 induced by C1 [183]
V 183 DEGV 184 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_183.vec
V 183 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_183.vec 0
% All degree centrality of 185. Subnetwork of N1 induced by C1 [184]
V 184 DEGV 185 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_184.vec
V 184 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_184.vec 0
% All degree centrality of 186. Subnetwork of N1 induced by C1 [185]
V 185 DEGV 186 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_185.vec
V 185 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_185.vec 0
% All degree centrality of 187. Subnetwork of N1 induced by C1 [186]
V 186 DEGV 187 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_186.vec
V 186 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_186.vec 0
% All degree centrality of 188. Subnetwork of N1 induced by C1 [187]
V 187 DEGV 188 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_187.vec
V 187 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_187.vec 0
% All degree centrality of 189. Subnetwork of N1 induced by C1 [188]
V 188 DEGV 189 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_188.vec
V 188 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_188.vec 0
% All degree centrality of 190. Subnetwork of N1 induced by C1 [189]
V 189 DEGV 190 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_189.vec
V 189 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_189.vec 0
% All degree centrality of 191. Subnetwork of N1 induced by C1 [190]
V 190 DEGV 191 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_190.vec
V 190 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_190.vec 0
% All degree centrality of 192. Subnetwork of N1 induced by C1 [191]
V 191 DEGV 192 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_191.vec
V 191 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_191.vec 0
% All degree centrality of 193. Subnetwork of N1 induced by C1 [192]
V 192 DEGV 193 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_192.vec
V 192 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_192.vec 0
% All degree centrality of 194. Subnetwork of N1 induced by C1 [193]
V 193 DEGV 194 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_193.vec
V 193 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_193.vec 0
% All degree centrality of 195. Subnetwork of N1 induced by C1 [194]
V 194 DEGV 195 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_194.vec
V 194 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_194.vec 0
% All degree centrality of 196. Subnetwork of N1 induced by C1 [195]
V 195 DEGV 196 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_195.vec
V 195 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_195.vec 0
% All degree centrality of 197. Subnetwork of N1 induced by C1 [196]
V 196 DEGV 197 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_196.vec
V 196 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_196.vec 0
% All degree centrality of 198. Subnetwork of N1 induced by C1 [197]
V 197 DEGV 198 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_197.vec
V 197 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_197.vec 0
% All degree centrality of 199. Subnetwork of N1 induced by C1 [198]
V 198 DEGV 199 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_198.vec
V 198 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_198.vec 0
% All degree centrality of 200. Subnetwork of N1 induced by C1 [199]
V 199 DEGV 200 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_199.vec
V 199 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_199.vec 0
% All degree centrality of 201. Subnetwork of N1 induced by C1 [200]
V 200 DEGV 201 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_200.vec
V 200 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_200.vec 0
% All degree centrality of 202. Subnetwork of N1 induced by C1 [201]
V 201 DEGV 202 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_201.vec
V 201 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_201.vec 0
% All degree centrality of 203. Subnetwork of N1 induced by C1 [202]
V 202 DEGV 203 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_202.vec
V 202 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_202.vec 0
% All degree centrality of 204. Subnetwork of N1 induced by C1 [203]
V 203 DEGV 204 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_203.vec
V 203 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_203.vec 0
% All degree centrality of 205. Subnetwork of N1 induced by C1 [204]
V 204 DEGV 205 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_204.vec
V 204 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_204.vec 0
% All degree centrality of 206. Subnetwork of N1 induced by C1 [205]
V 205 DEGV 206 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_205.vec
V 205 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_205.vec 0
% All degree centrality of 207. Subnetwork of N1 induced by C1 [206]
V 206 DEGV 207 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_206.vec
V 206 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_206.vec 0
% All degree centrality of 208. Subnetwork of N1 induced by C1 [207]
V 207 DEGV 208 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_207.vec
V 207 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_207.vec 0
% All degree centrality of 209. Subnetwork of N1 induced by C1 [208]
V 208 DEGV 209 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_208.vec
V 208 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_208.vec 0
% All degree centrality of 210. Subnetwork of N1 induced by C1 [209]
V 209 DEGV 210 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_209.vec
V 209 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_209.vec 0
% All degree centrality of 211. Subnetwork of N1 induced by C1 [210]
V 210 DEGV 211 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_210.vec
V 210 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_210.vec 0
% All degree centrality of 212. Subnetwork of N1 induced by C1 [211]
V 211 DEGV 212 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_211.vec
V 211 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_211.vec 0
% All degree centrality of 213. Subnetwork of N1 induced by C1 [212]
V 212 DEGV 213 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_212.vec
V 212 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_212.vec 0
% All degree centrality of 214. Subnetwork of N1 induced by C1 [213]
V 213 DEGV 214 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_213.vec
V 213 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_213.vec 0
% All degree centrality of 215. Subnetwork of N1 induced by C1 [214]
V 214 DEGV 215 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_214.vec
V 214 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_214.vec 0
% All degree centrality of 216. Subnetwork of N1 induced by C1 [215]
V 215 DEGV 216 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_215.vec
V 215 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_215.vec 0
% All degree centrality of 217. Subnetwork of N1 induced by C1 [216]
V 216 DEGV 217 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_216.vec
V 216 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_216.vec 0
% All degree centrality of 218. Subnetwork of N1 induced by C1 [217]
V 217 DEGV 218 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_217.vec
V 217 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_217.vec 0
% All degree centrality of 219. Subnetwork of N1 induced by C1 [218]
V 218 DEGV 219 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_218.vec
V 218 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_218.vec 0
% All degree centrality of 220. Subnetwork of N1 induced by C1 [219]
V 219 DEGV 220 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_219.vec
V 219 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_219.vec 0
% All degree centrality of 221. Subnetwork of N1 induced by C1 [220]
V 220 DEGV 221 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_220.vec
V 220 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_220.vec 0
% All degree centrality of 222. Subnetwork of N1 induced by C1 [221]
V 221 DEGV 222 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_221.vec
V 221 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_221.vec 0
% All degree centrality of 223. Subnetwork of N1 induced by C1 [222]
V 222 DEGV 223 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_222.vec
V 222 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_222.vec 0
% All degree centrality of 224. Subnetwork of N1 induced by C1 [223]
V 223 DEGV 224 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_223.vec
V 223 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_223.vec 0
% All degree centrality of 225. Subnetwork of N1 induced by C1 [224]
V 224 DEGV 225 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_224.vec
V 224 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_224.vec 0
% All degree centrality of 226. Subnetwork of N1 induced by C1 [225]
V 225 DEGV 226 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_225.vec
V 225 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_225.vec 0
% All degree centrality of 227. Subnetwork of N1 induced by C1 [226]
V 226 DEGV 227 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_226.vec
V 226 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_226.vec 0
% All degree centrality of 228. Subnetwork of N1 induced by C1 [227]
V 227 DEGV 228 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_227.vec
V 227 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_227.vec 0
% All degree centrality of 229. Subnetwork of N1 induced by C1 [228]
V 228 DEGV 229 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_228.vec
V 228 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_228.vec 0
% All degree centrality of 230. Subnetwork of N1 induced by C1 [229]
V 229 DEGV 230 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_229.vec
V 229 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_229.vec 0
% All degree centrality of 231. Subnetwork of N1 induced by C1 [230]
V 230 DEGV 231 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_230.vec
V 230 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_230.vec 0
% All degree centrality of 232. Subnetwork of N1 induced by C1 [231]
V 231 DEGV 232 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_231.vec
V 231 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_231.vec 0
% All degree centrality of 233. Subnetwork of N1 induced by C1 [232]
V 232 DEGV 233 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_232.vec
V 232 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_232.vec 0
% All degree centrality of 234. Subnetwork of N1 induced by C1 [233]
V 233 DEGV 234 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_233.vec
V 233 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_233.vec 0
% All degree centrality of 235. Subnetwork of N1 induced by C1 [234]
V 234 DEGV 235 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_234.vec
V 234 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_234.vec 0
% All degree centrality of 236. Subnetwork of N1 induced by C1 [235]
V 235 DEGV 236 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_235.vec
V 235 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_235.vec 0
% All degree centrality of 237. Subnetwork of N1 induced by C1 [236]
V 236 DEGV 237 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_236.vec
V 236 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_236.vec 0
% All degree centrality of 238. Subnetwork of N1 induced by C1 [237]
V 237 DEGV 238 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_237.vec
V 237 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_237.vec 0
% All degree centrality of 239. Subnetwork of N1 induced by C1 [238]
V 238 DEGV 239 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_238.vec
V 238 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_238.vec 0
% All degree centrality of 240. Subnetwork of N1 induced by C1 [239]
V 239 DEGV 240 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_239.vec
V 239 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_239.vec 0
% All degree centrality of 241. Subnetwork of N1 induced by C1 [240]
V 240 DEGV 241 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_240.vec
V 240 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_240.vec 0
% All degree centrality of 242. Subnetwork of N1 induced by C1 [241]
V 241 DEGV 242 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_241.vec
V 241 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_241.vec 0
% All degree centrality of 243. Subnetwork of N1 induced by C1 [242]
V 242 DEGV 243 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_242.vec
V 242 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_242.vec 0
% All degree centrality of 244. Subnetwork of N1 induced by C1 [243]
V 243 DEGV 244 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_243.vec
V 243 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_243.vec 0
% All degree centrality of 245. Subnetwork of N1 induced by C1 [244]
V 244 DEGV 245 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_244.vec
V 244 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_244.vec 0
% All degree centrality of 246. Subnetwork of N1 induced by C1 [245]
V 245 DEGV 246 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_245.vec
V 245 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_245.vec 0
% All degree centrality of 247. Subnetwork of N1 induced by C1 [246]
V 246 DEGV 247 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_246.vec
V 246 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_246.vec 0
% All degree centrality of 248. Subnetwork of N1 induced by C1 [247]
V 247 DEGV 248 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_247.vec
V 247 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_247.vec 0
% All degree centrality of 249. Subnetwork of N1 induced by C1 [248]
V 248 DEGV 249 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_248.vec
V 248 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_248.vec 0
% All degree centrality of 250. Subnetwork of N1 induced by C1 [249]
V 249 DEGV 250 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_249.vec
V 249 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_249.vec 0
% All degree centrality of 251. Subnetwork of N1 induced by C1 [250]
V 250 DEGV 251 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_250.vec
V 250 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_250.vec 0
% All degree centrality of 252. Subnetwork of N1 induced by C1 [251]
V 251 DEGV 252 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_251.vec
V 251 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_251.vec 0
% All degree centrality of 253. Subnetwork of N1 induced by C1 [252]
V 252 DEGV 253 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_252.vec
V 252 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_252.vec 0
% All degree centrality of 254. Subnetwork of N1 induced by C1 [253]
V 253 DEGV 254 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_253.vec
V 253 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_253.vec 0
% All degree centrality of 255. Subnetwork of N1 induced by C1 [254]
V 254 DEGV 255 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_254.vec
V 254 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_254.vec 0
% All degree centrality of 256. Subnetwork of N1 induced by C1 [255]
V 255 DEGV 256 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_255.vec
V 255 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_255.vec 0
% All degree centrality of 257. Subnetwork of N1 induced by C1 [256]
V 256 DEGV 257 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_256.vec
V 256 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_256.vec 0
% All degree centrality of 258. Subnetwork of N1 induced by C1 [257]
V 257 DEGV 258 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_257.vec
V 257 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_257.vec 0
% All degree centrality of 259. Subnetwork of N1 induced by C1 [258]
V 258 DEGV 259 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_258.vec
V 258 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_258.vec 0
% All degree centrality of 260. Subnetwork of N1 induced by C1 [259]
V 259 DEGV 260 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_259.vec
V 259 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_259.vec 0
% All degree centrality of 261. Subnetwork of N1 induced by C1 [260]
V 260 DEGV 261 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_260.vec
V 260 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_260.vec 0
% All degree centrality of 262. Subnetwork of N1 induced by C1 [261]
V 261 DEGV 262 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_261.vec
V 261 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_261.vec 0
% All degree centrality of 263. Subnetwork of N1 induced by C1 [262]
V 262 DEGV 263 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_262.vec
V 262 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_262.vec 0
% All degree centrality of 264. Subnetwork of N1 induced by C1 [263]
V 263 DEGV 264 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_263.vec
V 263 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_263.vec 0
% All degree centrality of 265. Subnetwork of N1 induced by C1 [264]
V 264 DEGV 265 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_264.vec
V 264 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_264.vec 0
% All degree centrality of 266. Subnetwork of N1 induced by C1 [265]
V 265 DEGV 266 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_265.vec
V 265 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_265.vec 0
% All degree centrality of 267. Subnetwork of N1 induced by C1 [266]
V 266 DEGV 267 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_266.vec
V 266 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_266.vec 0
% All degree centrality of 268. Subnetwork of N1 induced by C1 [267]
V 267 DEGV 268 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_267.vec
V 267 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_267.vec 0
% All degree centrality of 269. Subnetwork of N1 induced by C1 [268]
V 268 DEGV 269 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_268.vec
V 268 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_268.vec 0
% All degree centrality of 270. Subnetwork of N1 induced by C1 [269]
V 269 DEGV 270 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_269.vec
V 269 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_269.vec 0
% All degree centrality of 271. Subnetwork of N1 induced by C1 [270]
V 270 DEGV 271 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_270.vec
V 270 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_270.vec 0
% All degree centrality of 272. Subnetwork of N1 induced by C1 [271]
V 271 DEGV 272 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_271.vec
V 271 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_271.vec 0
% All degree centrality of 273. Subnetwork of N1 induced by C1 [272]
V 272 DEGV 273 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_272.vec
V 272 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_272.vec 0
% All degree centrality of 274. Subnetwork of N1 induced by C1 [273]
V 273 DEGV 274 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_273.vec
V 273 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_273.vec 0
% All degree centrality of 275. Subnetwork of N1 induced by C1 [274]
V 274 DEGV 275 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_274.vec
V 274 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_274.vec 0
% All degree centrality of 276. Subnetwork of N1 induced by C1 [275]
V 275 DEGV 276 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_275.vec
V 275 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_275.vec 0
% All degree centrality of 277. Subnetwork of N1 induced by C1 [276]
V 276 DEGV 277 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_276.vec
V 276 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_276.vec 0
% All degree centrality of 278. Subnetwork of N1 induced by C1 [277]
V 277 DEGV 278 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_277.vec
V 277 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_277.vec 0
% All degree centrality of 279. Subnetwork of N1 induced by C1 [278]
V 278 DEGV 279 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_278.vec
V 278 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_278.vec 0
% All degree centrality of 280. Subnetwork of N1 induced by C1 [279]
V 279 DEGV 280 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_279.vec
V 279 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_279.vec 0
% All degree centrality of 281. Subnetwork of N1 induced by C1 [280]
V 280 DEGV 281 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_280.vec
V 280 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_280.vec 0
% All degree centrality of 282. Subnetwork of N1 induced by C1 [281]
V 281 DEGV 282 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_281.vec
V 281 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_281.vec 0
% All degree centrality of 283. Subnetwork of N1 induced by C1 [282]
V 282 DEGV 283 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_282.vec
V 282 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_282.vec 0
% All degree centrality of 284. Subnetwork of N1 induced by C1 [283]
V 283 DEGV 284 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_283.vec
V 283 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_283.vec 0
% All degree centrality of 285. Subnetwork of N1 induced by C1 [284]
V 284 DEGV 285 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_284.vec
V 284 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_284.vec 0
% All degree centrality of 286. Subnetwork of N1 induced by C1 [285]
V 285 DEGV 286 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_285.vec
V 285 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_285.vec 0
% All degree centrality of 287. Subnetwork of N1 induced by C1 [286]
V 286 DEGV 287 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_286.vec
V 286 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_286.vec 0
% All degree centrality of 288. Subnetwork of N1 induced by C1 [287]
V 287 DEGV 288 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_287.vec
V 287 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_287.vec 0
% All degree centrality of 289. Subnetwork of N1 induced by C1 [288]
V 288 DEGV 289 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_288.vec
V 288 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_288.vec 0
% All degree centrality of 290. Subnetwork of N1 induced by C1 [289]
V 289 DEGV 290 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_289.vec
V 289 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_289.vec 0
% All degree centrality of 291. Subnetwork of N1 induced by C1 [290]
V 290 DEGV 291 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_290.vec
V 290 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_290.vec 0
% All degree centrality of 292. Subnetwork of N1 induced by C1 [291]
V 291 DEGV 292 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_291.vec
V 291 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_291.vec 0
% All degree centrality of 293. Subnetwork of N1 induced by C1 [292]
V 292 DEGV 293 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_292.vec
V 292 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_292.vec 0
% All degree centrality of 294. Subnetwork of N1 induced by C1 [293]
V 293 DEGV 294 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_293.vec
V 293 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_293.vec 0
% All degree centrality of 295. Subnetwork of N1 induced by C1 [294]
V 294 DEGV 295 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_294.vec
V 294 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_294.vec 0
% All degree centrality of 296. Subnetwork of N1 induced by C1 [295]
V 295 DEGV 296 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_295.vec
V 295 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_295.vec 0
% All degree centrality of 297. Subnetwork of N1 induced by C1 [296]
V 296 DEGV 297 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_296.vec
V 296 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_296.vec 0
% All degree centrality of 298. Subnetwork of N1 induced by C1 [297]
V 297 DEGV 298 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_297.vec
V 297 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_297.vec 0
% All degree centrality of 299. Subnetwork of N1 induced by C1 [298]
V 298 DEGV 299 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_298.vec
V 298 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_298.vec 0
% All degree centrality of 300. Subnetwork of N1 induced by C1 [299]
V 299 DEGV 300 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_299.vec
V 299 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_299.vec 0
% All degree centrality of 301. Subnetwork of N1 induced by C1 [300]
V 300 DEGV 301 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_300.vec
V 300 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_300.vec 0
% All degree centrality of 302. Subnetwork of N1 induced by C1 [301]
V 301 DEGV 302 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_301.vec
V 301 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_301.vec 0
% All degree centrality of 303. Subnetwork of N1 induced by C1 [302]
V 302 DEGV 303 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_302.vec
V 302 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_302.vec 0
% All degree centrality of 304. Subnetwork of N1 induced by C1 [303]
V 303 DEGV 304 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_303.vec
V 303 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_303.vec 0
% All degree centrality of 305. Subnetwork of N1 induced by C1 [304]
V 304 DEGV 305 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_304.vec
V 304 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_304.vec 0
% All degree centrality of 306. Subnetwork of N1 induced by C1 [305]
V 305 DEGV 306 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_305.vec
V 305 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_305.vec 0
% All degree centrality of 307. Subnetwork of N1 induced by C1 [306]
V 306 DEGV 307 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_306.vec
V 306 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_306.vec 0
% All degree centrality of 308. Subnetwork of N1 induced by C1 [307]
V 307 DEGV 308 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_307.vec
V 307 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_307.vec 0
% All degree centrality of 309. Subnetwork of N1 induced by C1 [308]
V 308 DEGV 309 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_308.vec
V 308 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_308.vec 0
% All degree centrality of 310. Subnetwork of N1 induced by C1 [309]
V 309 DEGV 310 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_309.vec
V 309 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_309.vec 0
% All degree centrality of 311. Subnetwork of N1 induced by C1 [310]
V 310 DEGV 311 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_310.vec
V 310 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_310.vec 0
% All degree centrality of 312. Subnetwork of N1 induced by C1 [311]
V 311 DEGV 312 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_311.vec
V 311 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_311.vec 0
% All degree centrality of 313. Subnetwork of N1 induced by C1 [312]
V 312 DEGV 313 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_312.vec
V 312 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_312.vec 0
% All degree centrality of 314. Subnetwork of N1 induced by C1 [313]
V 313 DEGV 314 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_313.vec
V 313 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_313.vec 0
% All degree centrality of 315. Subnetwork of N1 induced by C1 [314]
V 314 DEGV 315 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_314.vec
V 314 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_314.vec 0
% All degree centrality of 316. Subnetwork of N1 induced by C1 [315]
V 315 DEGV 316 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_315.vec
V 315 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_315.vec 0
% All degree centrality of 317. Subnetwork of N1 induced by C1 [316]
V 316 DEGV 317 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_316.vec
V 316 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_316.vec 0
% All degree centrality of 318. Subnetwork of N1 induced by C1 [317]
V 317 DEGV 318 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_317.vec
V 317 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_317.vec 0
% All degree centrality of 319. Subnetwork of N1 induced by C1 [318]
V 318 DEGV 319 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_318.vec
V 318 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_318.vec 0
% All degree centrality of 320. Subnetwork of N1 induced by C1 [319]
V 319 DEGV 320 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_319.vec
V 319 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_319.vec 0
% All degree centrality of 321. Subnetwork of N1 induced by C1 [320]
V 320 DEGV 321 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_320.vec
V 320 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_320.vec 0
% All degree centrality of 322. Subnetwork of N1 induced by C1 [321]
V 321 DEGV 322 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_321.vec
V 321 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_321.vec 0
% All degree centrality of 323. Subnetwork of N1 induced by C1 [322]
V 322 DEGV 323 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_322.vec
V 322 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_322.vec 0
% All degree centrality of 324. Subnetwork of N1 induced by C1 [323]
V 323 DEGV 324 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_323.vec
V 323 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_323.vec 0
% All degree centrality of 325. Subnetwork of N1 induced by C1 [324]
V 324 DEGV 325 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_324.vec
V 324 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_324.vec 0
% All degree centrality of 326. Subnetwork of N1 induced by C1 [325]
V 325 DEGV 326 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_325.vec
V 325 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_325.vec 0
% All degree centrality of 327. Subnetwork of N1 induced by C1 [326]
V 326 DEGV 327 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_326.vec
V 326 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_326.vec 0
% All degree centrality of 328. Subnetwork of N1 induced by C1 [327]
V 327 DEGV 328 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_327.vec
V 327 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_327.vec 0
% All degree centrality of 329. Subnetwork of N1 induced by C1 [328]
V 328 DEGV 329 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_328.vec
V 328 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_328.vec 0
% All degree centrality of 330. Subnetwork of N1 induced by C1 [329]
V 329 DEGV 330 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_329.vec
V 329 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_329.vec 0
% All degree centrality of 331. Subnetwork of N1 induced by C1 [330]
V 330 DEGV 331 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_330.vec
V 330 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_330.vec 0
% All degree centrality of 332. Subnetwork of N1 induced by C1 [331]
V 331 DEGV 332 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_331.vec
V 331 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_331.vec 0
% All degree centrality of 333. Subnetwork of N1 induced by C1 [332]
V 332 DEGV 333 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_332.vec
V 332 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_332.vec 0
% All degree centrality of 334. Subnetwork of N1 induced by C1 [333]
V 333 DEGV 334 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_333.vec
V 333 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_333.vec 0
% All degree centrality of 335. Subnetwork of N1 induced by C1 [334]
V 334 DEGV 335 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_334.vec
V 334 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_334.vec 0
% All degree centrality of 336. Subnetwork of N1 induced by C1 [335]
V 335 DEGV 336 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_335.vec
V 335 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_335.vec 0
% All degree centrality of 337. Subnetwork of N1 induced by C1 [336]
V 336 DEGV 337 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_336.vec
V 336 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_336.vec 0
% All degree centrality of 338. Subnetwork of N1 induced by C1 [337]
V 337 DEGV 338 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_337.vec
V 337 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_337.vec 0
% All degree centrality of 339. Subnetwork of N1 induced by C1 [338]
V 338 DEGV 339 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_338.vec
V 338 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_338.vec 0
% All degree centrality of 340. Subnetwork of N1 induced by C1 [339]
V 339 DEGV 340 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_339.vec
V 339 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_339.vec 0
% All degree centrality of 341. Subnetwork of N1 induced by C1 [340]
V 340 DEGV 341 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_340.vec
V 340 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_340.vec 0
% All degree centrality of 342. Subnetwork of N1 induced by C1 [341]
V 341 DEGV 342 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_341.vec
V 341 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_341.vec 0
% All degree centrality of 343. Subnetwork of N1 induced by C1 [342]
V 342 DEGV 343 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_342.vec
V 342 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_342.vec 0
% All degree centrality of 344. Subnetwork of N1 induced by C1 [343]
V 343 DEGV 344 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_343.vec
V 343 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_343.vec 0
% All degree centrality of 345. Subnetwork of N1 induced by C1 [344]
V 344 DEGV 345 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_344.vec
V 344 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_344.vec 0
% All degree centrality of 346. Subnetwork of N1 induced by C1 [345]
V 345 DEGV 346 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_345.vec
V 345 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_345.vec 0
% All degree centrality of 347. Subnetwork of N1 induced by C1 [346]
V 346 DEGV 347 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_346.vec
V 346 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_346.vec 0
% All degree centrality of 348. Subnetwork of N1 induced by C1 [347]
V 347 DEGV 348 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_347.vec
V 347 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_347.vec 0
% All degree centrality of 349. Subnetwork of N1 induced by C1 [348]
V 348 DEGV 349 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_348.vec
V 348 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_348.vec 0
% All degree centrality of 350. Subnetwork of N1 induced by C1 [349]
V 349 DEGV 350 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_349.vec
V 349 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_349.vec 0
% All degree centrality of 351. Subnetwork of N1 induced by C1 [350]
V 350 DEGV 351 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_350.vec
V 350 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_350.vec 0
% All degree centrality of 352. Subnetwork of N1 induced by C1 [351]
V 351 DEGV 352 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_351.vec
V 351 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_351.vec 0
% All degree centrality of 353. Subnetwork of N1 induced by C1 [352]
V 352 DEGV 353 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_352.vec
V 352 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_352.vec 0
% All degree centrality of 354. Subnetwork of N1 induced by C1 [353]
V 353 DEGV 354 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_353.vec
V 353 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_353.vec 0
% All degree centrality of 355. Subnetwork of N1 induced by C1 [354]
V 354 DEGV 355 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_354.vec
V 354 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_354.vec 0
% All degree centrality of 356. Subnetwork of N1 induced by C1 [355]
V 355 DEGV 356 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_355.vec
V 355 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_355.vec 0
% All degree centrality of 357. Subnetwork of N1 induced by C1 [356]
V 356 DEGV 357 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_356.vec
V 356 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_356.vec 0
% All degree centrality of 358. Subnetwork of N1 induced by C1 [357]
V 357 DEGV 358 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_357.vec
V 357 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_357.vec 0
% All degree centrality of 359. Subnetwork of N1 induced by C1 [358]
V 358 DEGV 359 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_358.vec
V 358 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_358.vec 0
% All degree centrality of 360. Subnetwork of N1 induced by C1 [359]
V 359 DEGV 360 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_359.vec
V 359 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_359.vec 0
% All degree centrality of 361. Subnetwork of N1 induced by C1 [360]
V 360 DEGV 361 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_360.vec
V 360 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_360.vec 0
% All degree centrality of 362. Subnetwork of N1 induced by C1 [361]
V 361 DEGV 362 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_361.vec
V 361 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_361.vec 0
% All degree centrality of 363. Subnetwork of N1 induced by C1 [362]
V 362 DEGV 363 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_362.vec
V 362 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_362.vec 0
% All degree centrality of 364. Subnetwork of N1 induced by C1 [363]
V 363 DEGV 364 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_363.vec
V 363 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_363.vec 0
% All degree centrality of 365. Subnetwork of N1 induced by C1 [364]
V 364 DEGV 365 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_364.vec
V 364 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_364.vec 0
% All degree centrality of 366. Subnetwork of N1 induced by C1 [365]
V 365 DEGV 366 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_365.vec
V 365 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_365.vec 0
% All degree centrality of 367. Subnetwork of N1 induced by C1 [366]
V 366 DEGV 367 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_366.vec
V 366 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_366.vec 0
% All degree centrality of 368. Subnetwork of N1 induced by C1 [367]
V 367 DEGV 368 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_367.vec
V 367 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_367.vec 0
% All degree centrality of 369. Subnetwork of N1 induced by C1 [368]
V 368 DEGV 369 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_368.vec
V 368 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_368.vec 0
% All degree centrality of 370. Subnetwork of N1 induced by C1 [369]
V 369 DEGV 370 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_369.vec
V 369 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_369.vec 0
% All degree centrality of 371. Subnetwork of N1 induced by C1 [370]
V 370 DEGV 371 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_370.vec
V 370 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_370.vec 0
% All degree centrality of 372. Subnetwork of N1 induced by C1 [371]
V 371 DEGV 372 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_371.vec
V 371 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_371.vec 0
% All degree centrality of 373. Subnetwork of N1 induced by C1 [372]
V 372 DEGV 373 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_372.vec
V 372 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_372.vec 0
% All degree centrality of 374. Subnetwork of N1 induced by C1 [373]
V 373 DEGV 374 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_373.vec
V 373 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_373.vec 0
% All degree centrality of 375. Subnetwork of N1 induced by C1 [374]
V 374 DEGV 375 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_374.vec
V 374 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_374.vec 0
% All degree centrality of 376. Subnetwork of N1 induced by C1 [375]
V 375 DEGV 376 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_375.vec
V 375 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_375.vec 0
% All degree centrality of 377. Subnetwork of N1 induced by C1 [376]
V 376 DEGV 377 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_376.vec
V 376 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_376.vec 0
% All degree centrality of 378. Subnetwork of N1 induced by C1 [377]
V 377 DEGV 378 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_377.vec
V 377 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_377.vec 0
% All degree centrality of 379. Subnetwork of N1 induced by C1 [378]
V 378 DEGV 379 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_378.vec
V 378 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_378.vec 0
% All degree centrality of 380. Subnetwork of N1 induced by C1 [379]
V 379 DEGV 380 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_379.vec
V 379 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_379.vec 0
% All degree centrality of 381. Subnetwork of N1 induced by C1 [380]
V 380 DEGV 381 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_380.vec
V 380 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_380.vec 0
% All degree centrality of 382. Subnetwork of N1 induced by C1 [381]
V 381 DEGV 382 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_381.vec
V 381 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_381.vec 0
% All degree centrality of 383. Subnetwork of N1 induced by C1 [382]
V 382 DEGV 383 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_382.vec
V 382 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_382.vec 0
% All degree centrality of 384. Subnetwork of N1 induced by C1 [383]
V 383 DEGV 384 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_383.vec
V 383 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_383.vec 0
% All degree centrality of 385. Subnetwork of N1 induced by C1 [384]
V 384 DEGV 385 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_384.vec
V 384 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_384.vec 0
% All degree centrality of 386. Subnetwork of N1 induced by C1 [385]
V 385 DEGV 386 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_385.vec
V 385 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_385.vec 0
% All degree centrality of 387. Subnetwork of N1 induced by C1 [386]
V 386 DEGV 387 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_386.vec
V 386 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_386.vec 0
% All degree centrality of 388. Subnetwork of N1 induced by C1 [387]
V 387 DEGV 388 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_387.vec
V 387 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_387.vec 0
% All degree centrality of 389. Subnetwork of N1 induced by C1 [388]
V 388 DEGV 389 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_388.vec
V 388 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_388.vec 0
% All degree centrality of 390. Subnetwork of N1 induced by C1 [389]
V 389 DEGV 390 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_389.vec
V 389 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_389.vec 0
% All degree centrality of 391. Subnetwork of N1 induced by C1 [390]
V 390 DEGV 391 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_390.vec
V 390 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_390.vec 0
% All degree centrality of 392. Subnetwork of N1 induced by C1 [391]
V 391 DEGV 392 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_391.vec
V 391 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_391.vec 0
% All degree centrality of 393. Subnetwork of N1 induced by C1 [392]
V 392 DEGV 393 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_392.vec
V 392 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_392.vec 0
% All degree centrality of 394. Subnetwork of N1 induced by C1 [393]
V 393 DEGV 394 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_393.vec
V 393 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_393.vec 0
% All degree centrality of 395. Subnetwork of N1 induced by C1 [394]
V 394 DEGV 395 [2]
% Saving vector to file   ---    C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_394.vec
V 394 WV C:\users\sarahricupero\Documents\Caffeine_SNA\Eras\Era23\Community_Degree_Files\total_degree_community_394.vec 0
